import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: { 
        flex: 1, 
        backgroundColor: "#046a38"
     },
    header: { 
        flexDirection: "row", 
        alignItems: "center", 
        backgroundColor: "#046a38", 
        padding: 10, 
        justifyContent: "center", 
        marginTop: 40 
    },
    logo: { 
        width: 40, 
        height: 40,
        marginRight: 10
    },
    headerText: { 
        fontSize: 14, 
        fontWeight: "bold", 
        color: "white" 
    },
    contentWrapper: { 
        flex: 1, 
        flexDirection: "row" 
    },
    sideTab: { 
        width: 60, 
        backgroundColor: "#034f2a", 
        alignItems: "center", 
        paddingTop: 20 
    },
    sideTabItem: { 
        padding: 15, 
        marginVertical: 10, 
        borderRadius: 5 
    },
    activeTab: { 
        backgroundColor: "#fff" 
    },
    sideTabText: { 
        fontSize: 20, 
        color: "white" 
    },
    mainContent: { 
        flex: 1, 
        padding: 20, 
        backgroundColor: "white" 
    },
    title: { 
        fontSize: 18, 
        fontWeight: "bold", 
        color: "black", 
        marginBottom: 10 
    },
    lessonButton: { 
        backgroundColor: "#fff", 
        padding: 10, 
        borderRadius: 5, 
        marginVertical: 5, 
        borderWidth: 1, 
        borderColor: "#046a38" 
    },
    lockedLesson: { 
        backgroundColor: "#d3d3d3" 
    }, 
    lessonText: { 
        fontSize: 16, 
        fontWeight: "bold", 
        color: "#046a38" 
    },
    lockIcon: { 
        position: "absolute", 
        right: 10, 
        top: 10 
    }, 
    dropdown: { 
        backgroundColor: "#ddd", 
        padding: 10, 
        borderRadius: 5, 
        marginLeft: 10, 
        marginBottom: 5 
    },
    dropdownItem: { 
        fontSize: 14, 
        paddingVertical: 5, 
        color: "#333" 
    },
    assignmentItem: { 
        backgroundColor: "#f9f9f9", 
        padding: 16, 
        borderRadius: 8, 
        marginVertical: 8, 
        borderWidth: 1, 
        borderColor: "#e0e0e0",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    assignmentContent: {
        flex: 1,
    },
    assignmentTitle: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#046a38",
        flex: 1, // Allow title to take available space
        marginRight: 8, // Add space between title and time limit
    },
    assignmentDescription: {
        fontSize: 14,
        color: "#666",
        marginBottom: 12,
        lineHeight: 20,
    },
    assignmentMeta: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    assignmentDeadline: {
        fontSize: 12,
        color: "#D32F2F",
        fontWeight: "500",
    },
    assignmentType: {
        fontSize: 12,
        color: "#666",
        fontStyle: "italic",
    },
    noAssignments: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
        marginTop: 50,
    },
    noAssignmentsText: {
        fontSize: 16,
        color: "#666",
        textAlign: 'center',
        lineHeight: 24,
    },
    assignmentText: { 
        fontSize: 16, 
        color: "#046a38" 
    },
    listContainer: {
        flex: 1,
    },
    listContentContainer: {
        paddingBottom: 20,
    },
    downloadButton: { 
        marginTop: 10, 
        backgroundColor: "#046a38", 
        padding: 10, 
        borderRadius: 5, 
        alignItems: "center" 
    },
    downloadText: { 
        color: "white", 
        fontSize: 14, 
        fontWeight: "bold" 
    },
    quizItem: { 
        backgroundColor: "#f9f9f9", 
        padding: 16, 
        borderRadius: 8, 
        marginVertical: 8, 
        borderWidth: 1, 
        borderColor: "#e0e0e0",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between"
    },
    quizContent: {
        flex: 1,
        marginRight: 10
    },
    quizTitle: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#046a38",
        flex: 1, // Allow title to take available space
        marginRight: 8, // Add space between title and time limit
    },
    quizDescription: {
        fontSize: 14,
        color: "#666",
        marginBottom: 12,
        lineHeight: 20,
    },
    quizMeta: {
        flexDirection: "row",
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 16,
    },
    quizDeadline: {
        fontSize: 12,
        color: "#ff6b35",
        fontWeight: "500"
    },
    quizType: {
        fontSize: 12,
        color: "#046a38",
        fontWeight: "500"
    },
    noQuizzes: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
        marginTop: 50,
    },
    noQuizzesText: {
        fontSize: 16,
        color: "#666",
        textAlign: "center",
        lineHeight: 24,
    },
    titleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 4,
    },
    timeLimitContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#e9ecef',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        marginLeft: 10,
    },
    timeLimitText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#495057',
        marginLeft: 4,
    },
    metaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 16,
    },
    metaItem: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    metaText: {
        fontSize: 12,
        color: '#495057',
        marginLeft: 5,
        fontWeight: '500',
    },
    metaSeparator: {
        fontSize: 12,
        color: '#adb5bd',
        marginHorizontal: -8,
    },


    subtitle: { 
        fontSize: 16, 
        fontWeight: "bold", 
        color: "#046a38", 
        marginTop: 10 
    },
    text: { 
        fontSize: 14, 
        color: "#333",
        marginVertical: 5 
    },
    analyticsContainer: { 
        backgroundColor: "#f8f8f8", 
        padding: 15, 
        borderRadius: 10, 
        marginTop: 10 
    },
    analyticsCard: { 
        backgroundColor: "#fff", 
        padding: 15, 
        borderRadius: 5, 
        marginVertical: 5, 
        shadowColor: "#000", 
        shadowOpacity: 0.1, 
        shadowRadius: 3, 
        elevation: 3 
    },
    analyticsTitle: { 
        fontSize: 16, 
        fontWeight: "bold", 
        color: "#046a38", 
        marginBottom: 5 
    },
    analyticsText: { 
        fontSize: 14, 
        color: "#333" 
    },
    performanceBar: { 
        height: 10, 
        backgroundColor: "#046a38", 
        borderRadius: 5,
        marginTop: 5 },
    handoutItem: {
        backgroundColor: "#fff",
        padding: 15,
        borderRadius: 8,
        marginVertical: 8,
        borderWidth: 1,
        borderColor: "#e0e0e0",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    handoutContent: {
        flex: 1,
    },
    handoutTitle: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#046a38",
        marginBottom: 5,
    },
    handoutDate: {
        fontSize: 12,
        color: "#666",
        marginBottom: 8,
    },
    handoutLink: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 5,
    },
    handoutLinkText: {
        fontSize: 12,
        color: "#666",
        marginLeft: 5,
    },
    noHandouts: {
        alignItems: "center",
        padding: 40,
    },
    noHandoutsText: {
        fontSize: 16,
        color: "#666",
        fontStyle: "italic",
    },
    lessonContentCard: {
        backgroundColor: "#f8f9fa",
        padding: 20,
        borderRadius: 12,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: "#e9ecef",
    },
    lessonIntroBox: {
        backgroundColor: "#fff3cd",
        padding: 15,
        borderRadius: 8,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: "#ffeaa7",
    },
    lessonIntroTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#856404",
        marginBottom: 10,
    },
    lessonIntroText: {
        fontSize: 14,
        color: "#856404",
        marginBottom: 5,
        lineHeight: 20,
    },
    lessonImagePlaceholder: {
        alignItems: "center",
        padding: 20,
        backgroundColor: "#f8f9fa",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#dee2e6",
    },
    lessonImageText: {
        fontSize: 14,
        color: "#6c757d",
        marginTop: 10,
    },
    lessonMainContent: {
        backgroundColor: "#fff",
        padding: 20,
        borderRadius: 12,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: "#e9ecef",
    },
    lessonSubtitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#046a38",
        marginTop: 20,
        marginBottom: 10,
    },
    lessonText: {
        fontSize: 14,
        color: "#333",
        marginBottom: 8,
        lineHeight: 20,
    },
    lessonNavigation: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
    },
    navButton: {
        backgroundColor: "#046a38",
        borderRadius: 8,
        alignItems: "center",
        flexDirection: "row",
        paddingVertical: 10,
        paddingHorizontal: 15,
    },
    navButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "bold",
    },
    pageIndicator: {
        backgroundColor: "#000",
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 2,
        borderColor: "#fff",
    },
    pageNumber: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "bold",
    },
    lessonViewer: {
        backgroundColor: "#fff",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#e9ecef",
        overflow: "hidden",
        marginBottom: 20,
    },
    lessonHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 15,
        backgroundColor: "#f8f9fa",
        borderBottomWidth: 1,
        borderBottomColor: "#e9ecef",
    },
    lessonProgress: {
        flex: 1,
    },
    lessonProgressText: {
        fontSize: 14,
        color: "#6c757d",
        marginBottom: 5,
    },
    progressBar: {
        height: 4,
        backgroundColor: "#e9ecef",
        borderRadius: 2,
        overflow: "hidden",
    },
    progressFill: {
        height: "100%",
        backgroundColor: "#046a38",
        width: "50%",
    },
    lessonMenuButton: {
        padding: 5,
    },
    lessonContentArea: {
    },
    lessonSection: {
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: "#f1f3f4",
    },
    sectionHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 15,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#046a38",
        marginLeft: 10,
    },
    contentBox: {
        backgroundColor: "#f8f9fa",
        padding: 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#e9ecef",
    },
    contentText: {
        fontSize: 14,
        color: "#333",
        marginBottom: 8,
        lineHeight: 20,
    },
    interactiveImage: {
        position: "relative",
        borderRadius: 8,
        overflow: "hidden",
    },
    lessonImage: {
        width: "100%",
        height: 200,
        borderRadius: 8,
    },
    imageOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "rgba(0,0,0,0.3)",
        justifyContent: "center",
        alignItems: "center",
    },
    playButton: {
        backgroundColor: "rgba(4, 106, 56, 0.8)",
        width: 60,
        height: 60,
        borderRadius: 30,
        justifyContent: "center",
        alignItems: "center",
    },
    algorithmTypes: {
        flexDirection: "row",
        justifyContent: "space-around",
        marginTop: 15,
    },
    algorithmType: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#fff",
        padding: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#046a38",
        minWidth: 100,
        justifyContent: "center",
    },
    algorithmTypeText: {
        fontSize: 14,
        color: "#046a38",
        marginLeft: 5,
        fontWeight: "500",
    },
    stepsContainer: {
        marginTop: 15,
    },
    stepItem: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 10,
        backgroundColor: "#fff",
        padding: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#e9ecef",
    },
    stepNumber: {
        backgroundColor: "#046a38",
        width: 30,
        height: 30,
        borderRadius: 15,
        justifyContent: "center",
        alignItems: "center",
        marginRight: 15,
    },
    stepNumberText: {
        color: "#fff",
        fontSize: 14,
        fontWeight: "bold",
    },
    stepText: {
        fontSize: 14,
        color: "#333",
        flex: 1,
    },
    pageControls: {
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
    },
    pageButton: {
        width: 35,
        height: 35,
        borderRadius: 17.5,
        backgroundColor: "#f8f9fa",
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#e9ecef",
    },
    pageButtonText: {
        fontSize: 14,
        color: "#6c757d",
        fontWeight: "500",
    },
    currentPage: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "#000",
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 2,
        borderColor: "#fff",
    },
    currentPageText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "bold",
    },
    handoutCard: {
        marginBottom: 20,
    },
    handoutViewer: {
        backgroundColor: "#fff",
        borderTopWidth: 1,
        borderTopColor: "#e9ecef",
        borderLeftWidth: 1,
        borderRightWidth: 1,
        borderBottomWidth: 1,
        borderLeftColor: "#e9ecef",
        borderRightColor: "#e9ecef",
        borderBottomColor: "#e9ecef",
        borderBottomLeftRadius: 8,
        borderBottomRightRadius: 8,
        overflow: "hidden",
    },
    viewerHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 15,
        backgroundColor: "#f8f9fa",
        borderBottomWidth: 1,
        borderBottomColor: "#e9ecef",
    },
    viewerTitle: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#046a38",
    },
    closeViewerButton: {
        padding: 5,
    },
    viewerContent: {
        padding: 20,
        minHeight: 200,
    },
    youtubeViewer: {
        alignItems: "center",
        justifyContent: "center",
    },
    youtubeHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 20,
        backgroundColor: "#fff3cd",
        padding: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#ffeaa7",
    },
    youtubeTitle: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#FF0000",
        marginLeft: 10,
    },
    videoPlayerContainer: {
        backgroundColor: "#000",
        borderRadius: 12,
        overflow: "hidden",
        marginBottom: 20,
        alignItems: "center",
        justifyContent: "center",
    },
    playButtonLarge: {
        backgroundColor: "rgba(255, 0, 0, 0.8)",
        width: 80,
        height: 80,
        borderRadius: 40,
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 15,
    },
    autoPlayText: {
        fontSize: 14,
        color: "#FF0000",
        fontWeight: "500",
        textAlign: "center",
    },
    videoInfo: {
        alignItems: "center",
        width: "100%",
    },
    videoUrl: {
        fontSize: 12,
        color: "#666",
        textAlign: "center",
        maxWidth: 250,
        marginBottom: 15,
    },
    openInYouTubeButton: {
        backgroundColor: "#FF0000",
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 8,
        gap: 8,
    },
    openInYouTubeText: {
        color: "#fff",
        fontSize: 14,
        fontWeight: "bold",
    },
    videoButtons: {
        flexDirection: "row",
        gap: 10,
        marginTop: 10,
    },
    openInBrowserButton: {
        backgroundColor: "#046a38",
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 8,
        gap: 8,
    },
    openInBrowserText: {
        color: "#fff",
        fontSize: 14,
        fontWeight: "bold",
    },
    fileViewer: {
        alignItems: "center",
        justifyContent: "center",
    },
    fileHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 20,
        backgroundColor: "#e8f5e8",
        padding: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#c8e6c9",
    },
    fileTitle: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#D32F2F",
        marginLeft: 10,
    },
    fileContainer: {
        alignItems: "center",
        width: "100%",
    },
    fileInfo: {
        alignItems: "center",
        marginBottom: 20,
    },
    fileName: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#046a38",
        marginTop: 10,
        marginBottom: 5,
        textAlign: "center",
    },
    fileUrl: {
        fontSize: 12,
        color: "#666",
        textAlign: "center",
        maxWidth: 250,
        marginBottom: 20,
    },
    autoOpenInfo: {
        alignItems: "center",
        backgroundColor: "#f8f9fa",
        padding: 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#e9ecef",
    },
    autoOpenText: {
        fontSize: 14,
        color: "#D32F2F",
        fontWeight: "500",
        textAlign: "center",
        marginBottom: 15,
    },
    openFileButton: {
        backgroundColor: "#046a38",
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 12,
        paddingHorizontal: 25,
        borderRadius: 8,
        gap: 10,
    },
    openFileButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "bold",
    },
    viewerCard: {
        backgroundColor: "#fff",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#e9ecef",
        marginTop: 10,
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 4,
        overflow: "hidden",
    },
    viewerCardHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 15,
        backgroundColor: "#f8f9fa",
        borderBottomWidth: 1,
        borderBottomColor: "#e9ecef",
    },
    viewerCardTitleSection: {
        flexDirection: "row",
        alignItems: "center",
        flex: 1,
    },
    viewerCardTitle: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#046a38",
        marginLeft: 10,
    },
    viewerCardContent: {
        padding: 20,
        minHeight: 200,
    },
    youtubeCard: {
        alignItems: "center",
        justifyContent: "center",
    },
    fileCard: {
        alignItems: "center",
        justifyContent: "center",
    },
    completedStep: {
        backgroundColor: "#e8f5e8",
        borderColor: "#4CAF50",
    },
    completedStepNumber: {
        backgroundColor: "#4CAF50",
    },
    paradigmList: {
        marginTop: 15,
    },
    paradigmItem: {
        backgroundColor: "#fff",
        padding: 15,
        borderRadius: 8,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: "#e9ecef",
        shadowColor: "#000",
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    paradigmName: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#046a38",
        marginBottom: 5,
    },
    paradigmDescription: {
        fontSize: 14,
        color: "#666",
        lineHeight: 18,
    },
    disabledButton: {
        backgroundColor: "#e9ecef",
    },
    disabledText: {
        color: "#ccc",
    },
    completedPage: {
        backgroundColor: "#e8f5e8",
        borderColor: "#4CAF50",
    },
    completedPageText: {
        color: "#4CAF50",
    },
    progressPercentage: {
        fontSize: 12,
        color: "#046a38",
        fontWeight: "500",
        marginTop: 2,
    },
    lessonHeaderActions: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    lessonActionButton: {
        padding: 8,
        borderRadius: 6,
        backgroundColor: "#f8f9fa",
        borderWidth: 1,
        borderColor: "#e9ecef",
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
    },
    lessonSummaryModal: {
        backgroundColor: "#fff",
        borderRadius: 16,
        width: "100%",
        maxHeight: "80%",
        shadowColor: "#000",
        shadowOpacity: 0.25,
        shadowRadius: 10,
        elevation: 10,
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: "#e9ecef",
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#046a38",
    },
    closeModalButton: {
        padding: 5,
    },
    modalHeaderButton: {
        padding: 5,
        marginLeft: 15,
    },
    modalContent: {
        padding: 20,
        maxHeight: 400,
    },
    summarySection: {
        marginBottom: 20,
    },
    summaryTitle: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#046a38",
        marginBottom: 10,
    },
    statItem: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: "#f1f3f4",
    },
    statLabel: {
        fontSize: 14,
        color: "#666",
    },
    statValue: {
        fontSize: 14,
        fontWeight: "bold",
        color: "#046a38",
    },
    noteItem: {
        backgroundColor: "#f8f9fa",
        padding: 12,
        borderRadius: 8,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: "#e9ecef",
    },
    notePage: {
        fontSize: 12,
        fontWeight: "bold",
        color: "#046a38",
        marginBottom: 4,
    },
    noteText: {
        fontSize: 14,
        color: "#333",
        lineHeight: 18,
    },
    noNotesText: {
        fontSize: 14,
        color: "#666",
        fontStyle: "italic",
        textAlign: "center",
        padding: 20,
    },
    bookmarkList: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
    },
    bookmarkItem: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#fff3cd",
        padding: 8,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: "#ffeaa7",
    },
    bookmarkText: {
        fontSize: 12,
        color: "#856404",
        marginLeft: 4,
        fontWeight: "500",
    },
    noBookmarksText: {
        fontSize: 14,
        color: "#666",
        fontStyle: "italic",
        textAlign: "center",
        padding: 20,
    },
    modalActions: {
        flexDirection: "row",
        padding: 20,
        borderTopWidth: 1,
        borderTopColor: "#e9ecef",
        gap: 10,
    },
    modalButton: {
        flex: 1,
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#e9ecef",
        alignItems: "center",
    },
    modalButtonText: {
        fontSize: 16,
        fontWeight: "500",
        color: "#666",
    },
    primaryButton: {
        backgroundColor: "#046a38",
        borderColor: "#046a38",
    },
    primaryButtonText: {
        color: "#fff",
    },
    videoSection: {
        backgroundColor: "#fff",
        padding: 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#e9ecef",
        marginBottom: 10,
    },
    videoHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 10,
    },
    videoTitle: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#046a38",
        marginLeft: 10,
        flex: 1,
    },
    videoDescription: {
        fontSize: 14,
        color: "#666",
        marginBottom: 15,
        lineHeight: 18,
    },
    playVideoButton: {
        backgroundColor: "#FF0000",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
        gap: 10,
    },
    playVideoText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "bold",
    },
    codeSection: {
        backgroundColor: "#fff",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#e9ecef",
        overflow: "hidden",
        marginBottom: 10,
    },
    codeHeader: {
        flexDirection: "row",
        alignItems: "center",
        padding: 15,
        backgroundColor: "#f8f9fa",
        borderBottomWidth: 1,
        borderBottomColor: "#e9ecef",
    },
    codeTitle: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#046a38",
        marginLeft: 10,
        flex: 1,
    },
    languageTag: {
        backgroundColor: "#046a38",
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    languageText: {
        color: "#fff",
        fontSize: 12,
        fontWeight: "bold",
    },
    codeContainer: {
        backgroundColor: "#2d3748",
        padding: 15,
    },
    codeText: {
        color: "#e2e8f0",
        fontSize: 12,
        fontFamily: "monospace",
        lineHeight: 18,
    },
    runCodeButton: {
        backgroundColor: "#4CAF50",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 10,
        paddingHorizontal: 15,
        gap: 8,
    },
    runCodeText: {
        color: "#fff",
        fontSize: 14,
        fontWeight: "bold",
    },
    comparisonContainer: {
        gap: 15,
    },
    languageCard: {
        backgroundColor: "#fff",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#e9ecef",
        padding: 15,
        shadowColor: "#000",
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    languageCardHeader: {
        marginBottom: 10,
    },
    languageName: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#046a38",
        marginBottom: 8,
    },
    paradigmTags: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 5,
    },
    paradigmTag: {
        backgroundColor: "#e3f2fd",
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#2196F3",
    },
    paradigmTagText: {
        fontSize: 11,
        color: "#1976D2",
        fontWeight: "500",
    },
    exampleContainer: {
        backgroundColor: "#f8f9fa",
        padding: 10,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: "#e9ecef",
    },
    exampleLabel: {
        fontSize: 12,
        fontWeight: "bold",
        color: "#666",
        marginBottom: 5,
    },
    exampleCode: {
        fontSize: 13,
        fontFamily: "monospace",
        color: "#333",
        backgroundColor: "#fff",
        padding: 8,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: "#dee2e6",
    },
    fileSection: {
        backgroundColor: "#fff",
        padding: 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#e9ecef",
        marginBottom: 10,
    },
    fileSectionHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 10,
    },
    fileSectionTitle: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#046a38",
        marginLeft: 10,
        flex: 1,
    },
    fileSectionDescription: {
        fontSize: 14,
        color: "#666",
        marginBottom: 15,
        lineHeight: 18,
    },
    pdfViewerContainer: {
        height: 400,
        backgroundColor: "#f8f9fa",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#e9ecef",
        marginBottom: 15,
        overflow: "hidden",
    },
    pdfViewer: {
        flex: 1,
        backgroundColor: "#fff",
    },
    pdfErrorContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
        backgroundColor: "#f8f9fa",
    },
    pdfErrorText: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#D32F2F",
        marginTop: 10,
        marginBottom: 5,
    },
    pdfErrorSubtext: {
        fontSize: 14,
        color: "#666",
        textAlign: "center",
        marginBottom: 20,
    },
    fallbackOpenButton: {
        backgroundColor: "#D32F2F",
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 8,
        gap: 8,
    },
    fallbackOpenButtonText: {
        color: "#fff",
        fontSize: 14,
        fontWeight: "bold",
    },
    fallbackButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 8,
        paddingHorizontal: 15,
        backgroundColor: "#f8f9fa",
        borderRadius: 6,
        borderWidth: 1,
        borderColor: "#e9ecef",
        gap: 5,
    },
    fallbackButtonText: {
        color: "#046a38",
        fontSize: 12,
        fontWeight: "500",
    },
    inlinePdfContainer: {
        height: 300,
        backgroundColor: "#f8f9fa",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#e9ecef",
        marginTop: 15,
        overflow: "hidden",
    },
    inlinePdfViewer: {
        flex: 1,
        backgroundColor: "#fff",
    },
    inlinePdfErrorContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
        backgroundColor: "#f8f9fa",
    },
    inlinePdfErrorText: {
        fontSize: 14,
        fontWeight: "bold",
        color: "#D32F2F",
        marginTop: 10,
        marginBottom: 15,
        textAlign: "center",
    },
    inlineFallbackButton: {
        backgroundColor: "#D32F2F",
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 8,
        paddingHorizontal: 15,
        borderRadius: 6,
        gap: 5,
    },
    inlineFallbackButtonText: {
        color: "#fff",
        fontSize: 12,
        fontWeight: "bold",
    },
    inlineVideoContainer: {
        height: 250,
        backgroundColor: "#000",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#e9ecef",
        marginBottom: 15,
        overflow: "hidden",
    },
    inlineVideoPlayer: {
        flex: 1,
        backgroundColor: "#000",
    },
    videoFallbackButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 8,
        paddingHorizontal: 15,
        backgroundColor: "#f8f9fa",
        borderRadius: 6,
        borderWidth: 1,
        borderColor: "#e9ecef",
        gap: 5,
    },
    videoFallbackButtonText: {
        color: "#FF0000",
        fontSize: 12,
        fontWeight: "500",
    },
    videoErrorContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
        backgroundColor: "#000",
    },
    videoErrorText: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#FF0000",
        marginTop: 10,
        marginBottom: 5,
        textAlign: "center",
    },
    videoErrorSubtext: {
        fontSize: 14,
        color: "#fff",
        textAlign: "center",
        marginBottom: 20,
    },
    videoErrorButton: {
        backgroundColor: "#FF0000",
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 8,
        gap: 8,
    },
    videoErrorButtonText: {
        color: "#fff",
        fontSize: 14,
        fontWeight: "bold",
    },
    debugInfo: {
        backgroundColor: "#f0f0f0",
        padding: 10,
        borderRadius: 5,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: "#ddd",
    },
    debugText: {
        fontSize: 12,
        color: "#666",
        fontFamily: "monospace",
    },
contentCard: {
  backgroundColor: '#fff',
  borderRadius: 12,
  padding: 16,
  marginBottom: 20,
  borderWidth: 1,
  borderColor: '#e9ecef',
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.05,
  shadowRadius: 2,
  elevation: 2,
},

contentCardHeader: {
  flexDirection: 'row',
  alignItems: 'center',
  marginBottom: 8,
},
contentCardTitle: {
  fontSize: 16,
  fontWeight: '600',
  color: '#343a40',
  marginLeft: 8,
  flex: 1,
},
contentCardDescription: {
  fontSize: 14,
  color: '#6c757d',
  marginBottom: 16,
  lineHeight: 20,
},
mediaContainer: {
  height: 250,
  borderRadius: 8,
  overflow: 'hidden',
  backgroundColor: '#f1f3f5',
  borderWidth: 1,
  borderColor: '#dee2e6',
},
mediaErrorContainer: {
  flex: 1,
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: '#f8f9fa',
  padding: 20,
},
mediaErrorText: {
  fontSize: 16,
  fontWeight: '500',
  color: '#495057',
  marginTop: 12,
  marginBottom: 16,
  textAlign: 'center',
},
mediaErrorButton: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: '#046a38',
  paddingVertical: 10,
  paddingHorizontal: 20,
  borderRadius: 20,
},
mediaErrorButtonText: {
  color: '#fff',
  fontWeight: '600',
  marginLeft: 8,
},

    noHandoutsMessage: {
        backgroundColor: "#e8f5e8",
        padding: 20,
        borderRadius: 8,
        marginBottom: 20,
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#c8e6c9",
    },
    noHandoutsTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#046a38",
        marginTop: 10,
        marginBottom: 8,
    },
    noHandoutsDescription: {
        fontSize: 14,
        color: "#2e7d32",
        textAlign: "center",
        lineHeight: 20,
    },


documentViewerModal: {
  height: '85%',
  width: '95%',
  backgroundColor: 'white',
  borderRadius: 10,
  padding: 0,
  overflow: 'hidden',
  elevation: 10,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.25,
  shadowRadius: 4,
},
documentViewerContent: {
  flex: 1,
  borderBottomLeftRadius: 10,
  borderBottomRightRadius: 10,
  overflow: 'hidden',
},
viewFileText: {
  marginTop: 8,
  fontSize: 14,
  color: '#046a38',
  fontWeight: 'bold',
},


  });
  
  